name: CI Execute Unit and Integration Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: [self-hosted]

    services:
      db:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: petclinic
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run Unit Tests
        id: unit-tests
        run: mvn test

      - name: Wait for Database to be Ready
        if: steps.unit-tests.outcome == 'success'
        run: |
          for i in {1..30}; do
            if mysqladmin ping -h 127.0.0.1 --silent; then
              echo "Database is ready!"
              break
            fi
            echo "Waiting for database..."
            sleep 2
          done

      - name: Run Integration Tests
        if: steps.unit-tests.outcome == 'success'
        run: mvn verify -P integration
